### PR TITLE
system_error_test: Enable locale query on MinGW-w64

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by pdimov** [comment]
`__MINGW32__` - any MinGW
`__MINGW64__` - MinGW-w64 in 64 bit mode
`__MINGW64_VERSION_MAJOR` - MinGW-w64 in both 64 and 32 bit modes

**Comment by Kojoley** [comment]
That's macro naming is... confusing. Also, MSYS2 which is Cygwin has `GetUserDefaultUILanguage` in my case, change Cygwin check to `!defined(__CYGWIN__) || defined(__MSYS__)`?

**Comment by pdimov** [comment]
I don't think `__MSYS__` matters. I have `GetUserDefaultUILanguage` everywhere - in Cygwin, Cygwin 64, MinGW-w64, MinGW 32. These checks seem outdated.

**Comment by Kojoley** [comment]
For Cygwin it seems outdated for 19 years https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=48ba505b8bc8671c7a2b243c816bf6f5b4451291, for MinGW-w64 7-12 years, I am not sure about MinGW. Should I remove them and leave only `!BOOST_PLAT_WINDOWS_RUNTIME`?

**Comment by pdimov** [comment]
Yes. Appveyor has all these so if it complains, we'll put them back in, but I doubt it.

**Pull request merged**
