### PR TITLE
Feature/do not include windows.h

### PR DESCRIPTION
**Pull request by jlodos**

### CODE REVIEW

**Comment by Beman** [comment]
Merged. Thanks!

--Beman

**Comment by Beman** [comment]
I had to revert this pull request. It worked fine with the msvc toolset, testing with the last four VC++ versions. But it failed with GCC version 4.9.3 (cygwin64). Below are the first few error messages. 

Please figure out the fix, and then submit another pull request.

Thanks,

--Beman

gcc.compile.c++ ..\..\..\bin.v2\libs\system\build\gcc-c++03\debug\link-static\error_code.o
In file included from ..\..\../boost/system/detail/error_code.ipp:25:0,
                 from ..\..\..\libs\system\src\error_code.cpp:19:
..\..\../boost/detail/winapi/error_handling.hpp: In function 'boost::detail::winapi::WORD_ boost::detail::winapi::MAKELANGID_(boost::detail::winapi::WORD_, boost::detail::winapi::WORD_)':
..\..\../boost/detail/winapi/error_handling.hpp:97:46: warning: conversion to 'boost::detail::winapi::WORD_ {aka short unsigned int}' from 'int' may alter its value [-Wconversion]
     return ((((WORD_)(s)) << 10) | (WORD_)(p));
                                              ^
In file included from ..\..\../boost/system/detail/error_code.ipp:24:0,
                 from ..\..\..\libs\system\src\error_code.cpp:19:
..\..\../boost/system/detail/error_code.ipp: In member function 'virtual boost::system::error_condition boost::system::{anonymous}::system_error_category::default_error_condition(int) const':
..\..\../boost/system/detail/error_code.ipp:284:10: error: a function call cannot appear in a constant-expression
     case ERROR_ACCESS_DENIED: return make_error_condition( permission_denied );
          ^
..\..\../boost/system/detail/error_code.ipp:285:10: error: a function call cannot appear in a constant-expression
     case ERROR_ALREADY_EXISTS: return make_error_condition( file_exists );
          ^
..\..\../boost/system/detail/error_code.ipp:286:10: error: a function call cannot appear in a constant-expression
     case ERROR_BAD_UNIT: return make_error_condition( no_such_device );
          ^
..\..\../boost/system/detail/error_code.ipp:287:10: error: a function call cannot appear in a constant-expression
     case ERROR_BUFFER_OVERFLOW: return make_error_condition( filename_too_long );
          ^

**Comment by jlodos** [comment]
The problem is in boost::detail::winapi. I have already submitted a pull request there. If/when it is merged I will make a new pull request. Thanks.

**Comment by jlodos** [comment]
There was also an error including winerror in the wrong order. It is not needed to include winerror.h at all, boost::detail::winapi takes care of that. Thanks.

**Pull request merged**
