### PR TITLE
Silence MSVC warnings about 'this' in base class initializer list.

### PR DESCRIPTION
**Pull request by Lastique**

### CODE REVIEW

**Comment by Beman** [comment]
Thanks Andrey and Peter,

--Beman

**Comment by Lastique** [comment]
The tests are green, can this PR be merged to master, please?

**Comment by pdimov** [comment]
This is not the only difference between develop and master, so I've been assuming that Beman would take care of merging them.

But I can cherry-pick this specific commit if it's urgent to do so.

**Comment by Lastique** [comment]
It's not urgent, I just don't want this to be forgotten in develop. If the change is to be merged along with other changes before 1.66, it's fine by me.

**Comment by pdimov** [comment]
OK, I merged the changes up to and including this commit to master, leaving the more recent ones up to Beman.

**Comment by Lastique** [comment]
Thank you, Peter.

**Comment by Beman** [comment]
OK, merged.

Thanks to both of you,

--Beman

**Pull request merged**
